### ISSUE TITLE
CLI args and argparse setup

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbag#12]
## The problem the component solves

Users need to be able to access the full functionality of mailbag over the command line. This will require user input that must be processed by mailbag.

## Type of component

- [x] Core
- [ ] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [X] Pull Request
- [ ] Comment with proposed solution

## Outcome

The mailbag tool will accept user input/args and make them available for processing with argparse.

## Major challenges or things to keep in mind

We may be able to utilize bagit-python's argparse for this, which will be easier than reinventing the wheel and make it easy to add new bagit-python functionality in the future.

**Comment by gwiedeman** [comment]
You should be able to add new args around line 18 in `mailbag/__init__.py` once Dave's PR is merged.

**Comment by haritgarg** [comment]
@gwiedeman I have tried to capture some arguments that might be required to perform some important functionalities of the project.
I have not added them in a code because the use case still needs to be discussed
I have listed some below, we will be able to specify more strongly when we will start creating the functionalities.
Please review and provide your feedback.

("--attachment", help = "attachments present or not")

mh11("--input_type", help = "input type MBOX/PST/IMAP")

sh20("--warc_with_css", help = "provide warc files which include embedded CSS")

sh24("--folder_info", help = "provide folder details like total no. of folders and emails")

ch36("--pdf_customizable_css", help = "outputs pdf with customizable css")

ch38("--export_email_header", help = "outputs headers of individual mails")

Reference from design document>>requirements
mh- must have
sh- should have
ch- could have
